/**
 * reconcile-session.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Quant Lab 1:1 Live Execution vs Historical Backtest Reconciliation Engine.
 * ─────────────────────────────────────────────────────────────────────────────
 * Cross-matches live trades captured by the Headless Daemon against the
 * deterministic historical replay generated by SweepReclaimEngine (Quant Lab).
 * Produces a 4-pillar parity audit report and Markdown comparison file.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import * as fs from 'fs';
import * as path from 'path';
import { SweepReclaimEngine, SweepReclaimScanConfig } from '../src/lib/quantEngine/SweepReclaimEngine';
import { DEFAULT_SR_LIVE_SETTINGS } from '../src/lib/quantEngine/strategyExecutionConfig';
import { fetchHistoricalKlines } from './lib/restBootstrap';
import { DaemonSessionLog } from './lib/daemonLedger';
import { Candle } from '../src/lib/fvgEngine';

// Parse CLI Arguments
const args = process.argv.slice(2);
const todayStr = new Date().toISOString().split('T')[0];
const targetDate = args.find((a) => a.startsWith('--date='))?.split('=')[1] || todayStr;
const symbol = (args.find((a) => a.startsWith('--symbol='))?.split('=')[1] || 'ETHUSDC').toUpperCase();

async function runReconciliation() {
  console.log(`\n===============================================================`);
  console.log(` 🔬 QUANT LAB 1:1 RECONCILIATION & AUDIT VERIFICATION ENGINE `);
  console.log(`===============================================================`);
  console.log(` Target Date:     ${targetDate}`);
  console.log(` Symbol:          ${symbol}`);
  console.log(` Comparison:      Live Daemon Log ⟷ Quant Lab Historical Engine`);
  console.log(`===============================================================\n`);

  // 1. Locate Live Daemon Session Log
  const runLogPath = path.join(process.cwd(), 'run_logs', `live_session_${targetDate}.json`);
  let liveSession: DaemonSessionLog | null = null;

  if (fs.existsSync(runLogPath)) {
    try {
      const raw = fs.readFileSync(runLogPath, 'utf8');
      liveSession = JSON.parse(raw);
      console.log(`[RECONCILE] ✅ Found Live Session Log: ${runLogPath}`);
      console.log(`[RECONCILE]    Recorded Live Trades: ${liveSession?.completedTrades?.length || 0}`);
    } catch (err: any) {
      console.warn(`[RECONCILE] ⚠️ Failed to parse live session log:`, err.message);
    }
  } else {
    console.log(`[RECONCILE] ℹ️ No live session log found for ${targetDate} (Will run backtest baseline).`);
  }

  // 2. Fetch Historical 5m Candles for the target date (including preceding 200 bars for anchor context)
  console.log(`[RECONCILE] 📥 Fetching 5m historical candles from Binance for ${targetDate}...`);
  const allCandles5m = await fetchHistoricalKlines(symbol, '5m', 1000);

  if (!allCandles5m || allCandles5m.length < 50) {
    console.error(`❌ [RECONCILE] Insufficient candle history fetched from Binance.`);
    process.exit(1);
  }

  // 3. Configure Quant Lab SweepReclaimEngine (Identical to Live Settings)
  const scanConfig: SweepReclaimScanConfig = {
    symbol,
    timeframe: '5m',
    anchorTypes: ['SWING_PIVOT', 'ASIAN_HIGH', 'ASIAN_LOW', 'LONDON_HIGH', 'LONDON_LOW', 'PDH', 'PDL'],
    lookbackMajor: 10,
    lookbackInternal: 5,
    maxBarsAnchorToSweep: 25,
    maxBarsSweepToReclaim: 10,
    maxBarsToRetest: 20,
    minSweepDepthAtrMultiplier: 0.10,
    slBufferAtrMultiplier: 0.12,
    entryMode: 'FVG_PROXIMAL',
    stage1Multiple: 1.0,
    stage2Multiple: 1.4,
    stage3Multiple: 3.0,
    enableStructuralTrail: true,
    enableProfitRatchet: true,
    volumeSmaPeriod: 20,
    volumeExpansionThreshold: 1.35,
    deltaDominanceThreshold: 52.0,
    bodyRatioThreshold: 0.50,
    requireThreePillarDisplacement: true,
    enforceDiscountPremiumGate: true,
  };

  const engine = new SweepReclaimEngine(scanConfig);
  const backtestResult = engine.scanHistoricalSetups(allCandles5m);
  const backtestSetups = backtestResult.setups || [];

  // Filter setups to target date
  const targetDaySetups = backtestSetups.filter((s) => {
    if (!s.reclaim_time) return false;
    const sDate = new Date(s.reclaim_time).toISOString().split('T')[0];
    return sDate === targetDate;
  });

  console.log(`[RECONCILE] 📊 Quant Lab Backtest identified ${targetDaySetups.length} setups on ${targetDate}.`);

  // 4. Perform 1:1 Cross-Matching
  const liveTrades = liveSession?.completedTrades || [];
  const reportRows: Array<{
    setupId: string;
    type: string;
    anchor: string;
    qlEntry: number;
    liveEntry: number | string;
    slippage: string;
    qlOutcome: string;
    liveOutcome: string;
    qlRealizedR: number;
    liveRealizedR: number | string;
    status: 'EXACT_MATCH' | 'SLIPPAGE_VARIANCE' | 'MISSED_IN_LIVE' | 'LIVE_EXTRA';
  }> = [];

  for (const qlSetup of targetDaySetups) {
    const qlEntry = qlSetup.retest_price || qlSetup.anchor_level;
    const expectedDir = qlSetup.type === 'BULLISH' ? 'LONG' : 'SHORT';
    const matchedLive = liveTrades.find(
      (t) =>
        t.originZoneId === qlSetup.id ||
        t.setupId === qlSetup.id ||
        (t.direction === expectedDir && Math.abs(t.entryPrice - qlEntry) < 2.0)
    );

    if (matchedLive) {
      const liveEntry = matchedLive.entryPrice;
      const slip = Math.abs(liveEntry - qlEntry);
      const slipStr = slip === 0 ? '$0.00' : `$${slip.toFixed(2)}`;
      const qlRealizedR = qlSetup.stage_exit_type === 'STAGE_2_WIN' ? 1.0 : qlSetup.stage_exit_type === 'FULL_TP3_WIN' ? 1.8 : -1.0;
      const liveRealizedR = matchedLive.realizedR || 0;

      const isOutcomeMatch =
        (matchedLive.exitReason?.includes('WIN') && qlSetup.stage_exit_type?.includes('WIN')) ||
        (matchedLive.exitReason?.includes('STOP') && qlSetup.stage_exit_type?.includes('STOP'));

      reportRows.push({
        setupId: qlSetup.id,
        type: qlSetup.type,
        anchor: qlSetup.anchor_name,
        qlEntry,
        liveEntry,
        slippage: slipStr,
        qlOutcome: qlSetup.stage_exit_type || 'N/A',
        liveOutcome: matchedLive.exitReason || 'N/A',
        qlRealizedR,
        liveRealizedR,
        status: isOutcomeMatch && slip < 0.5 ? 'EXACT_MATCH' : 'SLIPPAGE_VARIANCE',
      });
    } else {
      reportRows.push({
        setupId: qlSetup.id,
        type: qlSetup.type,
        anchor: qlSetup.anchor_name,
        qlEntry,
        liveEntry: 'UNFILLED / MISSED',
        slippage: 'N/A',
        qlOutcome: qlSetup.stage_exit_type || 'N/A',
        liveOutcome: 'NOT_RECORDED',
        qlRealizedR: 0,
        liveRealizedR: 'N/A',
        status: 'MISSED_IN_LIVE',
      });
    }
  }

  // 5. Generate Markdown Report
  let markdown = `# 🔬 Quant Lab 1:1 Reconciliation Parity Report\n\n`;
  markdown += `> **Date:** ${targetDate}  \n`;
  markdown += `> **Symbol:** ${symbol}  \n`;
  markdown += `> **Generated:** ${new Date().toISOString()}  \n\n`;

  markdown += `## 📋 Execution Comparison Matrix\n\n`;
  markdown += `| Setup ID | Type | Anchor | Quant Lab Entry | Live Entry | Slippage | Quant Lab Outcome | Live Outcome | Live R | Parity Status |\n`;
  markdown += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  for (const r of reportRows) {
    const badge =
      r.status === 'EXACT_MATCH'
        ? '✅ MATCH'
        : r.status === 'SLIPPAGE_VARIANCE'
        ? '⚠️ SLIPPAGE'
        : '❌ MISSED';
    markdown += `| \`${r.setupId}\` | **${r.type}** | ${r.anchor} | $${r.qlEntry.toFixed(2)} | ${typeof r.liveEntry === 'number' ? `$${r.liveEntry.toFixed(2)}` : r.liveEntry} | ${r.slippage} | ${r.qlOutcome} | ${r.liveOutcome} | ${r.liveRealizedR} | ${badge} |\n`;
  }

  markdown += `\n## 📊 Summary Parity Statistics\n\n`;
  const exactMatches = reportRows.filter((r) => r.status === 'EXACT_MATCH').length;
  const parityPct = reportRows.length > 0 ? ((exactMatches / reportRows.length) * 100).toFixed(1) : '100.0';

  markdown += `- **Total Setups Evaluated:** ${reportRows.length}\n`;
  markdown += `- **Exact Execution Matches:** ${exactMatches}\n`;
  markdown += `- **Execution Parity Score:** **${parityPct}%**\n\n`;

  const reportPath = path.join(process.cwd(), 'run_logs', `reconciliation_${targetDate}.md`);
  fs.writeFileSync(reportPath, markdown, 'utf8');

  console.log(`\n===============================================================`);
  console.log(` 📊 RECONCILIATION SUMMARY REPORT (${targetDate})`);
  console.log(`===============================================================`);
  console.log(` Total Setups Evaluated: ${reportRows.length}`);
  console.log(` Exact Matches:          ${exactMatches}`);
  console.log(` Parity Score:           ${parityPct}%`);
  console.log(` Report Saved:           ${reportPath}`);
  console.log(`===============================================================\n`);
}

runReconciliation().catch((err) => {
  console.error('[RECONCILIATION_ERROR]', err);
  process.exit(1);
});
